
services:
  postgres:
    restart: always
    container_name: level0-postgres
    image: postgres:latest
    environment: 
      POSTGRES_DB: "db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5433:5432"
    volumes:
      - ./scripts/postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
 
  app:
    restart: always
    container_name: level0-app
    build: .
    ports:
      - "8000:8080"
    environment: 
      POSTGRES_NAME: "db"
      POSTGRES_USER: "admin"
      POSTGRES_PASS: "admin"
    depends_on:
      - postgres

